### ISSUE TITLE
Add a clearer description in the about section

### ISSUE THREAD

**Issue by nshutijean** [rugwirobaker/helmes#15]
Please add more to **Sms service**

**Comment by rugwirobaker** [comment]
Example? What can you put that can be more helpful?

**Comment by nshutijean** [comment]
*Sms service* isn't bad but it is not self-descriptive
Example: An Sms service api/app that sends SMS messages to any supported carrier in Rwanda (more like this)

**Comment by rugwirobaker** [comment]
I like it.

**Comment by rugwirobaker** [comment]
Fixed by #17
